BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        TextInput:
            id: input_miles
            font_size: 48
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        id: output_label
        text: app.output_km
        font_size: 48
        color: (1, 1, 0, 1)
